# Generated by Django 5.0.6 on 2024-07-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.IntegerField(default=1),
        ),
    ]
