# Generated by Django 5.0.6 on 2024-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0002_coupon_min_purchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.IntegerField(),
        ),
    ]
