# Generated by Django 5.0.6 on 2024-09-19 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0003_alter_coupon_min_purchase_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_sales_delivered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_order_count', models.IntegerField()),
                ('coupon_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_offer_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
