# Generated by Django 5.0.6 on 2024-07-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('Return Requested', 'Return Requested'), ('Returned', 'Returned'), ('Rejected', 'Rejected')], default='none', max_length=100),
        ),
    ]
