# Generated by Django 5.0.6 on 2024-08-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0003_alter_coupon_min_purchase_amount'),
        ('orders', '0004_order_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminn.coupon'),
        ),
    ]
