# Generated by Django 5.0.6 on 2024-08-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_cancellation',
            name='cancel_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='order_cancellation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
