# Generated by Django 5.0.6 on 2024-06-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
