# Generated by Django 5.0.6 on 2024-08-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_productvarient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=300),
        ),
    ]
