# Generated by Django 5.0.6 on 2024-08-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_alter_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='product',
        ),
        migrations.AddField(
            model_name='product_image',
            name='varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.productvarient'),
        ),
    ]
