# Generated by Django 5.0.6 on 2024-08-20 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_remove_product_image_varient_product_image_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product_image',
            name='varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.productvarient'),
        ),
    ]
