# Generated by Django 5.0.6 on 2024-08-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_remove_product_image_product_productvarient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvarient',
            name='stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
