# Generated by Django 5.0.6 on 2024-08-20 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_remove_product_stock_productvarient_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='varient',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.product'),
        ),
        migrations.DeleteModel(
            name='ProductVarient',
        ),
    ]
