# Generated by Django 5.0.6 on 2024-08-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_remove_product_image_varient_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='blue'),
            preserve_default=False,
        ),
    ]
