# Generated by Django 5.0.6 on 2024-08-22 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_product_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Product.product'),
        ),
    ]
