# Generated by Django 5.0.6 on 2024-08-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_product_parent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent_product',
        ),
    ]
