# Generated by Django 5.0.6 on 2024-08-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_product_parent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent_product',
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='variants', to='Product.product'),
        ),
    ]
