# Generated by Django 5.0.6 on 2024-06-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
