# Generated by Django 5.0.6 on 2024-06-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
