# Generated by Django 5.0.6 on 2024-06-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_alter_user_address_pincode_cart_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
