# Generated by Django 5.0.6 on 2024-06-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_alter_user_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
