# Generated by Django 5.0.6 on 2024-06-28 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0013_user_address_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='phone_no',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator(message='phone number must be 10 digits long', regex='^\\d{10}$')]),
        ),
    ]
