# Generated by Django 5.0.6 on 2024-06-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0014_alter_user_address_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='phone_no',
        ),
    ]
