# Generated by Django 5.0.6 on 2024-06-28 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0015_remove_user_address_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='phone_no',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits long.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
