# Generated by Django 5.0.6 on 2024-06-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0016_user_address_phone_no_alter_user_address_pincode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_address',
            old_name='street',
            new_name='house_name',
        ),
    ]
