# Generated by Django 5.0.6 on 2024-08-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0022_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('Credit', 'credit'), ('debit', 'Debit')], max_length=10),
        ),
    ]
