# Generated by Django 5.0.6 on 2024-08-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0035_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Credit', 'credit'), ('debit', 'Debit'), ('refund', 'Refund')], max_length=10),
        ),
    ]
