# Generated by Django 5.0.6 on 2024-08-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0039_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('refund', 'Refund'), ('Credit', 'credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
